// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtqlmqawywhyfvxupggq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0cWxtcWF3eXdoeWZ2eHVwZ2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTA4NTksImV4cCI6MjA3Mzc2Njg1OX0.gRgMjaye_-ch3QUc7WDMIQxn4XY7G8yJGdw_HaB_cEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});